/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32 VS Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "main.h"
#include "gpio.h"

int main(void)
{
    CORE_ClockInit();
    CORE_PWRInit();
    GPIO_ConfigALL();
    RTC_Init();
    SERVO_TIMConfig(TIM1, TIM_CHANNEL_2);
    SERVO_SetAngle(TIM1, TIM_CHANNEL_2, 180);

    /* Loop forever */
    while (1)
    {
        CORE_EnterSTOP();
    }
}
